name: kravenhatcher
favicon: null
layout_spectrum: 0.07779657421633601
typography_spectrum: 0.6145044609438628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.815875445259735
  lightness: 0.6038995997514576
  saturation: 0.2390944752842188
  rhythmicContrast: 0.05933568556793034
purpose: []
